name: 'Flat Data'
description: 'The GitHub action which powers data fetching for Flat'
author: 'GitHub OCTO'
inputs:
  outfile_basename:
    description: '(Optional) The base filename to use for writing data, excluding the filename extension. An extension will be automatically chosen based on the response type.'
    default: 'data'
  http_url:
    description: 'A URL containing data to fetch.'
    required: false
  sql_format:
    description: "(Optional) The format of data to output. One of 'csv' or 'json'"
    default: 'json'
  sql_connstring:
    description: 'A connection string for making a SQL query.'
    required: false
  sql_queryfile:
    description: 'A SQL query to execute for fetching data.'
    required: false
    default: 'query.sql'
  postprocess:
    description: 'A path or URL to a deno postprocessing script.'
    required: false
outputs:
  delta_bytes: # size of changed data
    description: The overall number of bytes changed in the output data this run (current size - previous size)
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'purple'
  icon: 'download-cloud'
